#!/bin/sh
ln -sf {{pkg.path}}/api/package.json {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/api/app.js {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/api/node_modules {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/api/lib {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/api/controllers {{pkg.svc_var_path}}
ln -sf {{pkg.svc_config_path}}/config.json {{pkg.svc_var_path}}
